---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:  # Before committing, run Flake8 (to check PEP8)
      - id: flake8
        args: ["--max-line-length", "99"]
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:  # Force to run the linter
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
